create table EXPERIMENT
(
    ID INT NOT NULL AUTO_INCREMENT,
    ACRONYM VARCHAR(50) null,
    FULL_NAME VARCHAR(200) null,
    ADDRESS VARCHAR(200) null,
    PRIMARY KEY (ID)
);

CREATE TABLE MEMBER (
    ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    AGE INT NOT NULL,
    EXPERIMENT_ID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT(ID)
);